apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: azure-blob        