apiVersion: v1 
kind: PersistentVolume
metadata:
  name: tukano-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: standard
  hostPath:
    path: /usr/local/tomcat/tukano-pv  