apiVersion: v1
kind: ConfigMap
metadata:
  name: users-service-config
data:
    USERS_DB_URL: "https://cosmos70070northeurope.documents.azure.com:443/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorts-service  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shorts-service
  template:
    metadata:
      labels:
        app: shorts-service   
    spec:
      containers:
        - name: shorts-service
          image: tim0ns/shorts-service:latest
          ports:
          - containerPort: 3000 
          env:
          - name: USERS_CONTAINER
            value: "http://127.0.0.1:3002/tukano-1/rest/users/"     
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi
          livenessProbe:
            httpGet:
              path: /
              port: 3002
          readinessProbe:
            httpGet:
              path: /
              port: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: shorts-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
    app: shorts              