apiVersion: v1
kind: PersistentVolume
metadata:
  name: tukano-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: tukano-storage
  hostPath:
    path: /data/my-dynamic-pv
